# Generated by Django 4.1 on 2024-11-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subkategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkategori', to='homepage.kategorijasa')),
            ],
        ),
        migrations.CreateModel(
            name='SesiLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subkategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.subkategori')),
            ],
        ),
        migrations.CreateModel(
            name='PesananJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskon', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Mencari Pekerja Terdekat', 'Mencari Pekerja Terdekat'), ('Pesanan Selesai', 'Pesanan Selesai')], default='Menunggu Pembayaran', max_length=50)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('pekerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.pekerja')),
                ('sesi_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.sesilayanan')),
                ('subkategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.subkategori')),
            ],
        ),
        migrations.AddField(
            model_name='pekerja',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.subkategori'),
        ),
    ]
