# Generated by Django 4.1 on 2024-11-13 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodeBayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pekerja',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='pekerja',
            name='nama',
        ),
        migrations.AddField(
            model_name='pekerja',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerja', to='homepage.subkategori'),
        ),
        migrations.AlterField(
            model_name='sesilayanan',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_layanan', to='homepage.subkategori'),
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PekerjaKategoriJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.kategorijasa')),
                ('pekerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.pekerja')),
            ],
        ),
    ]
